url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/bogardpd" # the subpath of your site, e.g. /blog
title: "Paul Bogard’s Portfolio" # the name of your site, e.g. ACME Corp.

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /blog/:categories/:year-:month-:day-:title/

collections:
  flight_historian_versions:
    output: true
    sort_by: release_date
    permalink: /flight-historian/:title/